spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/dbsell?characterEncoding=utf-8&useSSL=false
girl:
  name: hery
  age: 25
env:
  dev
